name: Release

on:
  release:
    types: [published]
  push:
    branches:
      - master

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:

  buildForWindows:
    name: Build for Windows 🗗
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
      
      - name: Cache library
        uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library
      
      - name: Build project
        uses: webbertakken/unity-builder@v0.11
        with:
          projectPath: /HohimBrueh
          unityVersion: 2019.3.0f1
          targetPlatform: StandaloneWindows64

      - name: Zip up output
        run: |
          cd build
          ls
          cd StandaloneWindows64-2019.3.0f1
          cd build/StandaloneWindows64-2019.3.0f1
          sudo mv StandaloneWindows64 StandaloneWindows64.exe
          zip -r ../../Windows64.zip *

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Windows64
          path: build/StandaloneWindows64-2019.3.0f1

      - name: Attach to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: Windows64.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  buildForMac:
    name: Build for OSX 🍏
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
      
      - name: Cache library
        uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library
      
      - uses: webbertakken/unity-builder@v0.11
        with:
          projectPath: /HohimBrueh
          unityVersion: 2019.3.0f1
          targetPlatform: StandaloneOSX

      - name: Zip up output
        run: |
          cd build
          ls
          cd StandaloneOSX-2019.3.0f1
          zip -r ../../OSX.zip *

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: OSX
          path: build/StandaloneOSX-2019.3.0f1

      - name: Attach to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: OSX.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  buildForLinux:
    name: Build for Linux 🐧
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
      
      - name: Cache library
        uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library
      
      - uses: webbertakken/unity-builder@v0.11
        with:
          projectPath: /HohimBrueh
          unityVersion: 2019.3.0f1
          targetPlatform: StandaloneLinux64

      - run: |
          cd build/StandaloneLinux64-2019.3.0f1
          zip -r ../../Linux.zip *

      - uses: actions/upload-artifact@v1
        with:
          name: Linux
          path: build/StandaloneLinux64-2019.3.0f1

      - uses: JasonEtco/upload-to-release@master
        with:
          args: Linux.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}