name: Release

on:
  release:
    types: [published]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:

  buildForWindows:
    name: Build for Windows 🗗
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
      
      - name: Cache library
        uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library
      
      - name: Build project
        uses: webbertakken/unity-builder@v0.11
        with:
          projectPath: /HohimBrueh
          unityVersion: 2019.3.0f1
          targetPlatform: StandaloneWindows64

      - name: Zip up output
        run: |
          cd build/StandaloneWindows64
          ls
          zip -r ../../Windows64.zip *

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Windows64
          path: build/StandaloneWindows64

      - name: Attach to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: Windows64.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  buildForMac:
    name: Build for OSX 🍏
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
      
      - name: Cache library
        uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library
      
      - name: Build project
        uses: webbertakken/unity-builder@v0.11
        with:
          projectPath: /HohimBrueh
          unityVersion: 2019.3.0f1
          targetPlatform: StandaloneOSX

      - name: Zip up output
        run: |
          cd build/StandaloneOSX
          zip -r ../../OSX.zip *

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: OSX
          path: build/StandaloneOSX

      - name: Attach to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: OSX.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}