name: Release

on:
  release:
    types: [published]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  requestActivation:
    name: Request activation ✔
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v1

      # Activate Unity
      - name: Unity - Activate
        uses: webbertakken/unity-activate@v1
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

  testRunnerInEditMode:
    name: Test in editmode 📝
    runs-on: ubuntu-latest
    steps:
      # Checkout repository (required to test local actions)
      - name: Checkout repository
        uses: actions/checkout@v1

      # Configure test runner
      - name: Run tests
        id: testRunner
        uses: webbertakken/unity-test-runner@v1
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_PROJECT_PATH: /HohimBrueh
          TEST_MODE: editmode

      # Upload artifact
      - name: Expose as artifact
        uses: actions/upload-artifact@v1
        with:
          name: Test results (edit mode)
          path: ${{ steps.testRunner.outputs.artifactsPath }}

  buildForWindows:
    name: Build for Windows 🗗
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: webbertakken/unity-builder@v0.5
        with:
          projectPath: /HohimBrueh
          unityVersion: 2019.2.11f1
          targetPlatform: StandaloneWindows64
      - run: |
          cd build/StandaloneWindows64-2019.2.11f1
          sudo mv StandaloneWindows64 StandaloneWindows64.exe
          zip -r ../../Windows64.zip *
      - uses: actions/upload-artifact@v1
        with:
          name: Windows64
          path: build/StandaloneWindows64-2019.2.11f1
      - uses: JasonEtco/upload-to-release@master
        with:
          args: Windows64.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  buildForMac:
    name: Build for OSX 🍏
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: webbertakken/unity-builder@v0.5
        with:
          projectPath: /HohimBrueh
          unityVersion: 2019.2.11f1
          targetPlatform: StandaloneOSX
      - run: |
          cd build/StandaloneOSX-2019.2.11f1
          zip -r ../../OSX.zip *
      - uses: actions/upload-artifact@v1
        with:
          name: OSX
          path: build/StandaloneOSX-2019.2.11f1
      - uses: JasonEtco/upload-to-release@master
        with:
          args: OSX.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  buildForLinux:
    name: Build for Linux 🐧
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: webbertakken/unity-builder@v0.5
        with:
          projectPath: /HohimBrueh
          unityVersion: 2019.2.11f1
          targetPlatform: StandaloneLinux64
      - run: |
          cd build/StandaloneLinux64-2019.2.11f1
          zip -r ../../Linux.zip *
      - uses: actions/upload-artifact@v1
        with:
          name: Linux
          path: build/StandaloneLinux64-2019.2.11f1
      - uses: JasonEtco/upload-to-release@master
        with:
          args: Linux.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}